### ISSUE TITLE
Print styles for KLL quake maps 

### ISSUE THREAD

**Issue by lxbarth** [osmlab/mapbox-studio-humanitarian-print.tm2#1]
From @geohacker

> Relaying from Kathmandu Living Labs - 
> They need high res print maps for these areas to begin with - 
> - kalinchowk
> - bahrabise
> - charikot
> - larpak
> - warpak
> 
> KLL has a website for this - http://kathmandulivinglabs.github.io/quake-maps/
> @planemad and I have been doing this - http://geohacker.in/nepal/
> #### tags they need -
> - temples, schools, fuel, fire, hospital, office
> 
> Some of these aren't available on mapbox-streets. What's the best way to do this?
> Since much of the mapping is still in progress, we'll need to refresh these maps. 
> 
> Help? @lxbarth @ajashton @amyleew @aaronlidman

**Comment by lxbarth** [comment]
- @aaronlidman pulling together data / architecture now
- @amyleew pulling together a map style + documentation

Goal by end of the day Monday Eastern time:
1. Get a print map from the first locations above up
2. Share our work in an open repo with KLL and HOT community

cc @planemad @geohacker

**Comment by dalekunce** [comment]
Can you add amenity=drinking_water

**Comment by aaronlidman** [comment]
:+1: @dalekunce 
- I'm going to source anything fire related from [OpenFireMap](http://wiki.openstreetmap.org/wiki/OpenFireMap#Presentation_on_the_map).
- office=*
- amenity=drinking_water

Open to more, setting up scripts now.

**Comment by planemad** [comment]
also `amenity=public_building`

**Comment by amyleew** [comment]
@dalekunce @planemad - Where can I find the Emerald style started here http://geohacker.in/nepal/ ?

**Comment by amyleew** [comment]
@dalekunce @planemad - Currently working with this style: [American Red Cross HDM style](https://api.tiles.mapbox.com/v4/americanredcross.939fa02b/page.html?access_token=pk.eyJ1IjoibXNsZWUiLCJhIjoiclpiTWV5SSJ9.P_h8r37vD8jpIH1A6i1VRg#8/40.604/-78.143)

**Comment by amyleew** [comment]
@dalekunce @planemad - No worries on style above ... starting with a fresh Emerald style.

**Comment by dalekunce** [comment]
The ARC HDM style is really a mess don't worry about using it.

**Comment by aaronlidman** [comment]
- vector tiles are at `aaronlidman.ycnjnhfr` mapid
- here are the tags considered: https://gist.github.com/aaronlidman/d0905e0f7b83b38b1df1
- using the geofabirk extract found here: http://wiki.openstreetmap.org/wiki/2015_Nepal_earthquake

**Comment by amyleew** [comment]
@lxbarth [List with lat / long of five locations](https://gist.github.com/amyleew/fd470ab56ed4857b5754) for A4 print crops. 

@aaronlidman is ensuring data pulled is relevant in [those locations](https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/issues/1#issue-71303680)

**Comment by amyleew** [comment]
@aaronlidman - Final style updates and export .pngs for print:

[Kalinchok, Kuri Village, Central Region, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#17/27.74714/86.03230)
![kuri_z17](https://cloud.githubusercontent.com/assets/4587826/7359571/b010b5d0-ed0d-11e4-8471-80364a0a042e.png)

[Bahrabise, Central Region, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#14/27.7970573/85.9195447)
![bhaktapur_z16](https://cloud.githubusercontent.com/assets/4587826/7359618/58ae6142-ed0e-11e4-80ee-5d4390086f04.png)

[Charikot, Bhimeshwor Municipality, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#16/27.6667/86.0529)
![charikot_z16](https://cloud.githubusercontent.com/assets/4587826/7359627/82e96402-ed0e-11e4-995c-df9f98b2ce55.png)

[Laprak, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#15/28.2119/84.8069)
![laprak_z15](https://cloud.githubusercontent.com/assets/4587826/7359646/ac16df4e-ed0e-11e4-8b7e-02dc6219e8b8.png)

[Barpak, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#16/28.2016/84.7448)
![barpak_z15](https://cloud.githubusercontent.com/assets/4587826/7359664/f225b76c-ed0e-11e4-9711-9932747b51f3.png)

## Additional Locations

Since requested areas don't have much coverage from the custom dataset, here are areas with more coverage of `fire_hydrants` and `drinking_water` POIs.

[Kirtipur, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#15/27.674901128890223/85.27832508087158)
![kirtipur_z15](https://cloud.githubusercontent.com/assets/4587826/7359972/5f00326e-ed13-11e4-8dc5-f032ce62a0fc.png)

[Chasukhel, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#17/27.67208/85.42993)
![chasukhel_z17](https://cloud.githubusercontent.com/assets/4587826/7360010/d42f39f4-ed13-11e4-8ccf-06b6df824b6e.png)

[Dolakha, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#18/27.67795/86.07402)
![dolakha_z18](https://cloud.githubusercontent.com/assets/4587826/7360012/da9b7758-ed13-11e4-9eff-4cf6b8b2bee0.png)

/cc @lxbarth

**Comment by geohacker** [comment]
@amyleew @aaronlidman thank you so much for this! Sending it across to KLL.

**Comment by geohacker** [comment]
@amyleew - 

per voice with Prabhas of KLL - 

> i think no matter what, making the roads more prominent is helpful making the hillshade lighter and the green a bit lighter would also help

Can we optimise the style for black and white printing? They don't seem to have a colour printer around.

**Comment by lxbarth** [comment]
Moving to a separate ticket https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/issues/2
